<?php
/**
 * @file
 * Module file for starting drupal dev
 */

/**
 * Implements of hook_init().
 */
function starting_drupal_dev_init() {
  drupal_set_message('Our module is alive!');
}

/**
 * Implements hook_menu().
 */
function starting_drupal_dev_menu() {
  $items['starting_drupal_dev/custom/%node'] = array(
    'title' => 'Custom page',
    'page callback' => 'starting_drupal_dev_custom',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Custom callback function.
 */
function starting_drupal_dev_custom($node) {
  // View of node
  $content = node_view($node);

  return $content;
}

/**
 * Implements hook_user_login().
 */
function starting_drupal_dev_user_login(&$edit, $account) {
  drupal_set_message(t('Hi @name, thank you for logging in and welcome!', array('@name' => $account->name)));
}

/**
 * Implements hook_form_alter().
 */
function starting_drupal_dev_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'article_node_form') {
    $form['field_message'] = array(
      '#type' => 'item',
      '#title' => t('New article'),
      '#markup' => t('You are about to create a new article'),
    );
  }
}
