<?php
/**
 * @file
 * Module file for starting drupal dev
 */

/**
 * Implements of hook_init().
 */
function starting_drupal_dev_init() {
  drupal_set_message('Our module is alive!');
}

/**
 * Implements hook_menu().
 */
function starting_drupal_dev_menu() {
  $items['starting_drupal_dev/custom/%node'] = array(
    'title' => 'Custom page',
    'page callback' => 'starting_drupal_dev_custom',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Custom callback function.
 */
function starting_drupal_dev_custom($node) {
  // View of node
  $content = node_view($node);

  return $content;
}

/**
 * Implements hook_user_login().
 */
function starting_drupal_dev_user_login(&$edit, $account) {
  drupal_set_message(t('Thank you for logging in and welcome!'));
}